{# Copyright (c) Pelagicore AB 2016 #}
{% import "qtcpp.j2" as cpp %}
{{ cpp.autogenerated()}}
{% set module_name = 'Qml{0}Module'.format(module.module_name) %}

#include "plugin.h"

#include <qqml.h>

#include "generated/{{module_name|lower}}.h"

{% for interface in module.interfaces %}
#include "{{interface|lower}}.h"
{% endfor %}

void Plugin::registerTypes(const char *uri)
{
    {{module_name}}::registerTypes();
    // @uri {{module|lower}}
    {{module_name}}::registerQmlTypes(uri, 1, 0);
{% for interface in module.interfaces %}
    {{interface}}::registerQmlTypes(uri, 1, 0);
{% endfor %}
}
