# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Release

on:
  # Triggers the workflow when a release is created
  release:
    types: [created]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-test.yml

  upload:
    uses: ./.github/workflows/python-package.yml
    needs: [ build ]
    with:
      use_testpypi: false
